// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/service.proto
//
// To regenerate, run:
//   protoc --go_out=. --go-grpc_out=. api/proto/service.proto

package pb

// HealthCheckRequest 健康检查请求
type HealthCheckRequest struct {
	Service string `json:"service,omitempty"`
}

// HealthCheckResponse_ServingStatus 服务状态
type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// HealthCheckResponse 健康检查响应
type HealthCheckResponse struct {
	Status HealthCheckResponse_ServingStatus `json:"status,omitempty"`
}

// HelloRequest 问候请求
type HelloRequest struct {
	Name string `json:"name,omitempty"`
}

// HelloResponse 问候响应
type HelloResponse struct {
	Message string `json:"message,omitempty"`
	TraceId string `json:"trace_id,omitempty"`
}
